baseurl = "https://rmccarth.info"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "orange"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "rmccarth"
    subtitle = "MSISPM '20"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Rob McCarthy"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "Home"
        name = "/"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "Highlights"
        name = "Highlights"
        url = "/post/highlights"
